module.exports = {
  EMIT: {
    TIEMPO_RESTANTE: 'TIEMPO_RESTANTE',
    LECCION_TERMINADA:'TERMINADA',
    EMPEZAR_LECCION: 'EMPEZAR_LECCION'
  },
  LECCION_PAUSADA: 'Lección pausada',
  TERMINAR: 'TERMINAR_LECCION',
  COMENZAR: 'COMENZAR_LECCION',
  AUMENTAR_TIEMPO: 'AUMENTAR_TIEMPO_LECCION',
  PAUSAR: 'PAUSAR_LECCION',
  CONTINUAR: 'CONTINUAR_LECCION',
  RESPUESTA_ESTUDIANTE: 'RESPUESTA_ESTUDIANTE',
  USUARIO: 'USUARIO',
  RECONECTAR_ESTUDIANTE: 'RECONECTAR_ESTUDIANTE',
  RECONECTAR_MODERADOR: 'RECONECTAR_MODERADOR',
  ESTUDIANTES_CONECTADOS: 'ESTUDIANTES_CONECTADOS',
  NUEVO_ESTUDIANTE: 'NUEVO_ESTUDIANTE_CONECTADO'
}